package kpgx

import (
	"context"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgconn"
)

// DBTX is the interface that matches both *pgxpool.Pool and pgx.Tx.
// It is compatible with the interface generated by sqlc.
type DBTX interface {
	Exec(context.Context, string, ...interface{}) (pgconn.CommandTag, error)
	Query(context.Context, string, ...interface{}) (pgx.Rows, error)
	QueryRow(context.Context, string, ...interface{}) pgx.Row
}

// GetDBTX returns the transaction from the context if present,
// otherwise it returns the underlying pool from the DB.
// This allows sqlc queries to automatically participate in transactions
// if they are running within a RunInTx block.
func (db *DB) GetDBTX(ctx context.Context) DBTX {
	if tx, ok := TxFromContext(ctx); ok {
		return tx
	}
	return db.pool
}
